# Generated by Django 3.2.7 on 2021-11-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0002_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.CharField(default='', max_length=5),
        ),
    ]
