# Generated by Django 3.2 on 2022-02-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0005_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(default='', max_length=400)),
                ('no_likes', models.IntegerField(default=0)),
                ('no_comments', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenta.location')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Licenta.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenta.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenta.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=150)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenta.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenta.customuser')),
            ],
        ),
    ]
