# Generated by Django 3.2 on 2022-03-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0012_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='Licenta.customuser')),
                ('follower', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='Licenta.customuser')),
            ],
        ),
    ]
