# Generated by Django 3.2 on 2022-03-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0014_customuser_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenta.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenta.customuser')),
            ],
        ),
    ]
