# Generated by Django 3.2 on 2022-04-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0017_notification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
