# Generated by Django 3.2 on 2022-04-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0018_location_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='descriere',
            field=models.CharField(default='', max_length=200),
        ),
    ]
