# Generated by Django 3.2 on 2022-04-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0019_location_descriere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='descriere',
            new_name='description',
        ),
    ]
