# Generated by Django 3.2 on 2022-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0020_rename_descriere_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
