# Generated by Django 3.2 on 2022-04-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0021_alter_location_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedlocations',
            name='points',
        ),
    ]
