# Generated by Django 3.2 on 2022-04-24 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0024_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 24)),
        ),
    ]
