# Generated by Django 3.2 on 2022-04-29 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Licenta', '0026_auto_20220425_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 29)),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenta.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenta.customuser')),
            ],
        ),
    ]
